# Number of parallel VMs to run
parallel: 3
# kernel versions to test
kernel_versions:
    - v6.4
    - v6.6.119
    - v6.12.62
      #- v6.17.12 # disabled due to qemu's "unable to handle EFI zboot image with "zstd" compression" error
      #- v6.18.1 # disabled due to qemu's "unable to handle EFI zboot image with "zstd" compression" error
