name: bpf tests

on:
  push:
  pull_request:

jobs:
  test:
    name: test-${{ matrix.arch }}
    runs-on: ${{ (matrix.arch == 'arm64' && 'ubuntu-24.04-arm') || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"
      - name: Install system dependencies for eBPF build
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libelf-dev \
            clang \
            llvm \
            libbpf-dev
      - name: Generate eBPF code
        run: |
          make generate-ebpf
          go test -c ./internal/bpf/... -o tester
      - name: Validate bpf tests using bpfvalidator
        uses: ./.github/actions/bpfvalidator
        with:
          args: |
            --config=$GITHUB_WORKSPACE/bpfvalidator-${{ matrix.arch }}-config.yaml --cmd="$GITHUB_WORKSPACE/tester -test.v"
          arch: ${{ matrix.arch }}
