name: E2E Tests

on:
  pull_request:

jobs:
  test-e2e:
    name: E2E test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: "go.mod"

      - name: Running Test e2e
        run: |
          make test-e2e
      - name: Upload cluster logs
        if: failure()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: e2e-test-cluster-logs
          path: test/e2e/logs
          if-no-files-found: error
          retention-days: 7
